
name: Build & Deploy
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: npm install

    - name: Build Files
      run: npm run build
         
    - name: Copy Files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        source: ./
        target: ~/Vite-Application/
        rm: true

    - name: SSH into the remote server and execute script
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            cd ~/Vite-Application
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm use 18
            npm install pm2 -g
            pm2 restart Vite-Application
